version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: videoflix
      POSTGRES_USER: martin
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    image: europe-west6-docker.pkg.dev/videoflix-439014/videoflix/web-image:latest
    command: gunicorn videoflix_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static-data:/usr/src/app/staticfiles
      - media-data:/usr/src/app/media
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"

  nginx:
    image: europe-west6-docker.pkg.dev/videoflix-439014/videoflix/nginx-image:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - static-data:/usr/src/app/staticfiles
      - media-data:/usr/src/app/media
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt 
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rq-worker:
    image: europe-west6-docker.pkg.dev/videoflix-439014/videoflix/rq-worker-image:latest
    command: python manage.py rqworker default
    volumes:
      - media-data:/usr/src/app/media
    depends_on:
      - redis
    environment:
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"

  certbot:
    image: certbot/certbot
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'


volumes:
  postgres-data:
  static-data:
  media-data:

