version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: videoflix
      POSTGRES_USER: martin
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn videoflix_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  pgdata:

