# Generated by Django 4.2.16 on 2024-11-05 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_video_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchhistory',
            name='videos',
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='last_watched',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='timestamp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.video'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
