# Generated by Django 4.2.16 on 2024-11-05 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_video_category'),
        ('watch_history', '0002_remove_watchhistory_videos_watchhistory_last_watched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='video',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='content.video'),
        ),
    ]
