# Generated by Django 4.2.16 on 2024-11-05 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_video_category'),
        ('watch_history', '0004_alter_watchhistory_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.video'),
        ),
    ]
