# Generated by Django 4.2.16 on 2024-11-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_history', '0006_alter_watchhistory_last_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='last_watched',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
