# Generated by Django 4.2.16 on 2024-10-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_hls_playlist_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_playlist',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
