# Generated by Django 4.2.16 on 2024-10-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_video_hls_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='hls_playlist',
            new_name='hls_file_1080',
        ),
        migrations.AddField(
            model_name='video',
            name='hls_file_360',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='hls_file_480',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='hls_file_720',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
