# Generated by Django 4.2.16 on 2024-11-03 16:38

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_hls_playlist_video_hls_file_1080_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='teaser',
            field=models.FileField(blank=True, null=True, upload_to=content.models.video_upload_to),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.thumbnail_upload_to),
        ),
    ]
