# Generated by Django 4.2.16 on 2024-11-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_video_teaser_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('documentary', 'Documentary'), ('drama', 'Drama'), ('romance', 'Romance')], max_length=20, null=True),
        ),
    ]
