# Generated by Django 4.2.16 on 2024-11-10 16:17

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('documentary', 'Documentary'), ('drama', 'Drama'), ('romance', 'Romance')], default='documentary', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='teaser',
            field=models.FileField(default='media/defaults/default_video.mp4', upload_to=content.models.video_upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='media/defaults/default_thumbnail.jpg', upload_to=content.models.thumbnail_upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='media/defaults/default_video.mp4', upload_to=content.models.video_upload_to),
            preserve_default=False,
        ),
    ]
